version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: finance-tracker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 